import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navBar";
import SideBar from "@/components/sideBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PICTURE GALLERY",
  description: "Generated by Saud Ahmed",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <NavBar/>
        <div className="flex">
          <div className=" w-2/12"><SideBar/></div>
          <div className="w-full">{children}</div>
        </div>

        
      </body>
    </html>
  );
}
